# Generated by Django 4.0 on 2023-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_aadhar_number_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'phone_number': 'Enter a valid phone number'}, null=True),
        ),
    ]
