# Generated by Django 4.1 on 2022-10-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_items_saled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
