# Generated by Django 4.1 on 2022-10-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_productdetails_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=30)),
                ('product_quantity', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='date',
        ),
    ]
