# Generated by Django 4.1 on 2022-10-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_productdetailsdate_remove_productdetails_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetailsDate',
        ),
    ]
