# Generated by Django 4.1 on 2022-10-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_delete_productdetailsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
