# Generated by Django 4.1 on 2022-10-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_productdetails_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='expiry',
        ),
    ]
