# Generated by Django 4.1 on 2022-10-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_productdetails_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
