# Generated by Django 4.1 on 2022-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_productdetails_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
