# Generated by Django 4.1 on 2022-10-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_productdetails_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=30)),
                ('Phone_number', models.IntegerField()),
            ],
        ),
    ]
