# Generated by Django 4.1 on 2022-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_todaypatients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
