# Generated by Django 4.1 on 2022-10-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_healthhistory_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patientdetails'),
        ),
    ]
