# Generated by Django 4.1 on 2022-10-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_healthhistory_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthhistory',
            old_name='history',
            new_name='treatment_details',
        ),
    ]
