# Generated by Django 4.1 on 2022-10-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_prescribedmedicine_treatment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
