# Generated by Django 4.1 on 2022-10-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_billsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsmodel',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.patientdetails'),
            preserve_default=False,
        ),
    ]
