# Generated by Django 4.1 on 2022-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_billsmodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsmodel',
            name='bill_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
