# Generated by Django 4.1 on 2022-10-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_billsmodel_bill_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Date_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='patientdetails',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
