# Generated by Django 4.1 on 2022-10-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_rename_address_patientdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
