# Generated by Django 4.1 on 2022-10-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_user_aadhar_number_user_address_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_user',
        ),
    ]
