# Generated by Django 4.1.2 on 2022-10-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_alter_birthfield_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthField',
        ),
    ]
