# Generated by Django 4.1.2 on 2022-10-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_generalvitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalvitals',
            name='patient',
        ),
    ]
