# Generated by Django 4.1.2 on 2022-10-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_remove_generalvitals_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvitals',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.patientdetails'),
            preserve_default=False,
        ),
    ]
