# Generated by Django 4.1.2 on 2022-10-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_alter_todaypatients_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
