# Generated by Django 4.1.2 on 2022-10-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_user_pan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
