# Generated by Django 4.1.2 on 2022-10-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_alter_patientdetails_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='age',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='blood_group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
