# Generated by Django 4.1.2 on 2022-10-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_remove_patientdetails_age_patientdetails_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
