# Generated by Django 4.1.2 on 2022-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_patientdetails_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalvitals',
            old_name='blood_pressure',
            new_name='blood_pressure_end',
        ),
        migrations.AddField(
            model_name='generalvitals',
            name='blood_pressure_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
