# Generated by Django 4.1.2 on 2022-10-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_rename_blood_pressure_generalvitals_blood_pressure_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='age',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
