# Generated by Django 4.1.2 on 2022-10-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_addfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfees',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
