# Generated by Django 4.0.4 on 2022-10-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_remove_addfees_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
