# Generated by Django 4.0.4 on 2022-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_alter_generalvitals_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfees',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
