# Generated by Django 4.0.4 on 2022-10-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_alter_addfees_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfees',
            name='fee_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
