# Generated by Django 4.0.4 on 2022-11-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_alter_patientdetails_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralVitals_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure_start', models.IntegerField()),
                ('blood_pressure_end', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('others', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.patientdetails')),
            ],
        ),
    ]
