# Generated by Django 4.0.4 on 2022-11-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_generalvitals_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaypatients',
            name='is_vital',
            field=models.BooleanField(default=False),
        ),
    ]
