# Generated by Django 4.0.4 on 2022-11-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_allergy_medicine_vitals_alter_fees_vitals_and_more'),
        ('management', '0064_todaypatients_is_vital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralVitals',
        ),
    ]
