# Generated by Django 4.0.4 on 2022-11-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_delete_generalvitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaypatients',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals_new'),
        ),
    ]
