# Generated by Django 4.0.4 on 2022-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_todaypatients_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaypatients',
            name='is_consulted',
            field=models.BooleanField(default=False),
        ),
    ]
