# Generated by Django 4.0.4 on 2022-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_todaypatients_is_consulted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvitals_new',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
