# Generated by Django 4.0.4 on 2022-11-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_alter_generalvitals_new_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvitals_new',
            name='is_consulted',
            field=models.BooleanField(default=False),
        ),
    ]
