# Generated by Django 4.0.4 on 2022-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('medicine_brand', models.CharField(max_length=200)),
                ('medicine_id', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('medicine_mg', models.DecimalField(decimal_places=2, max_digits=16)),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('stocked_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
        ),
    ]
