# Generated by Django 4.0.4 on 2022-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_patient_medicine_fees_allergy_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medicine',
            name='diagnose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_medicine',
            name='lab_test',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_medicine',
            name='symptom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
