# Generated by Django 4.0.4 on 2022-10-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_remove_addfees_patient'),
        ('inventory', '0005_remove_patient_medicine_lab_test_lab_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy_medicine',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals'),
        ),
        migrations.AddField(
            model_name='fees',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals'),
        ),
        migrations.AddField(
            model_name='patient_medicine',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals'),
        ),
    ]
