# Generated by Django 4.0.4 on 2022-11-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_alter_patientdetails_phone_number'),
        ('inventory', '0007_code_medicine_medicine_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_medicine',
            name='diagnose',
        ),
        migrations.RemoveField(
            model_name='patient_medicine',
            name='symptom',
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(blank=True, null=True)),
                ('diagnose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.patientdetails')),
                ('vitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals')),
            ],
        ),
    ]
