# Generated by Django 4.0.4 on 2022-11-03 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_todaypatients_is_vital'),
        ('inventory', '0008_remove_patient_medicine_diagnose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy_medicine',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals_new'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals_new'),
        ),
        migrations.AlterField(
            model_name='lab_test',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals_new'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals_new'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.generalvitals_new'),
        ),
    ]
