# Generated by Django 4.0.4 on 2022-11-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_code_medicine_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medicine',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
