# Generated by Django 4.0.4 on 2022-11-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_medicine_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_medicine',
            name='min_quantity',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
